version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: js-envs-performance-comparison-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5555
    volumes:
      - ./server/data:/app/data
    networks:
      - app-network
    ports:
      - "5555:5555"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5555
    container_name: js-envs-performance-comparison-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge