version: '3.8'

services:
  client:
    build: 
      context: ./client
      args:
        - VITE_NODE_API_URL=http://runtimer.ru/node-api
        - VITE_DENO_API_URL=http://runtimer.ru/deno-api
        - VITE_BUN_API_URL=http://runtimer.ru/bun-api
    ports:
      - "3000:80"
    depends_on:
      - node-server
      - deno-server
      - bun-server
    networks:
      - app-network

  node-server:
    build: ./node-server
    container_name: node-server
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
    networks:
      - app-network

  deno-server:
    build: ./deno-server
    container_name: deno-server
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    networks:
      - app-network

  bun-server:
    build: ./bun-server
    container_name: bun-server
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
    networks:
      - app-network

networks:
  app-network:
    driver: bridge